### ISSUE TITLE
erreta

### ISSUE THREAD

**Issue by akrsnr** [markjprice/cs8dotnetcore3#1]
At the beginning of page 203, the following is written.

> Stack memory is faster to work with (because it is managed directly by the CPU
> and because it uses a **frst-in, frst-out** mechanism, it is more likely to have the data
> in its L1 or L2 cache) but limited in size, while heap memory is slower but much
> more plentiful.

But I think it should be

> Stack memory is faster to work with (because it is managed directly by the CPU
> and because it uses a **last-in, frst-out** mechanism, it is more likely to have the data
> in its L1 or L2 cache) but limited in size, while heap memory is slower but much
> more plentiful.

**Comment by markjprice** [comment]
Thanks! I have added this to an errata.md.
