### ISSUE TITLE
NorthwindML trained models in repo & book differ from newly generated

### ISSUE THREAD

**Issue by rovercoder** [markjprice/cs8dotnetcore3#10]
1. Cloned this repo
2. Removed PracticalApps/NorthwindML/wwwroot/Data
- Germany-model.zip
- UK-model.zip
- USA-model.zip
3. dotnet run
4. Retrained models and getting different results from the ones shown in screenshots / presently in repo:
[Germany-model.zip](https://github.com/markjprice/cs8dotnetcore3/files/4536558/Germany-model.zip)
[UK-model.zip](https://github.com/markjprice/cs8dotnetcore3/files/4536559/UK-model.zip)
[USA-model.zip](https://github.com/markjprice/cs8dotnetcore3/files/4536560/USA-model.zip)

**Comment by markjprice** [comment]
Hi @rovercoder, I had hoped to resolve this when I came to update the ML.NET chapter for the sixth edition. But my publisher and I have decided to remove it to make space for a new chapter about service topics like gRPC that will be more useful to more readers. So I am unlikely to dig into why you get different results to me. Sorry!
