### ISSUE TITLE
Evidently ".NET Native" project has been renamed to 'CoreRT"

### ISSUE THREAD

**Issue by chipascc** [markjprice/cs8dotnetcore3#16]
Their new README also states that they are an experimental project and that they don't expect to be productized.
I don't know if you want to add that to the errata or not.

Love the book!  Will be using it as the textbook for my C# class in the fall.

**Comment by markjprice** [comment]
Thanks for the comment, @chipascc. .NET Native seemed like it might be an important technology three years ago but not so much now so I plan to remove mention of it from the next edition.

I'm happy to hear that you will be using my book as the textbook for your C# class. I hope that covid-19 isn't going to stop your classes. Good luck!
