### ISSUE TITLE
errata 

### ISSUE THREAD

**Issue by lacostaplans** [markjprice/cs8dotnetcore3#2]
In Windows, to create **Northwind.db**, de command in TERMINAL:

`sqlite3 Northwind.db < Northwind.sql`

generate the error:

```
En línea: 1 Carácter: 22
     + sqlite3 Northwind.db < Northwind.sql
     +                      ~
     El operador '<' está reservado para uso futuro.
```

The command must be:

`sqlite3 Northwind.db -init Northwind.sql`

**Comment by yeahe83** [comment]
sqlite3 Northwind.db ".read Northwind.sql"

**Comment by markjprice** [comment]
Thanks! I have added this to an errata.md file.
