### ISSUE TITLE
The Result doesn't sort as expected

### ISSUE THREAD

**Issue by abdollahkahne** [markjprice/cs8dotnetcore3#20]
I use your example in page 412 which Joins Categories and Products in `Northwind.db`.
As you mentioned in the result and I expected the result should be sorted by Categories because it is outer sequence. But the result for me always sorted on `Product.ProductID`.
Any hint for why this happens? Am I wrong about something?
I am using Ubuntu 20.04 and SQLite.
Thanks in advances
Code is as follows just for mentioning:

`
```
var queryJoin = db.Categories.Join(
                    db.Products, cat => cat.CategoryID,
                    p => p.CategoryID, (c, p) => new
                    {
                        c.CategoryName,
                        p.ProductName,
                        p.ProductID
                    }
                );
                foreach (var item in queryJoin)
                {
                    WriteLine("{0}: {1} is in {2}", item.ProductID, item.ProductName, item.CategoryName);

                }
                WriteLine();
```
`

**Comment by markjprice** [comment]
This seems to be change in default behaviour for EF Core. If a specific sort order is needed then it is now best to specify it explicitly. I have fixed this in the fifth edition and I will add it to the fourth edition errata. Thanks!
