### ISSUE TITLE
Missing solutions for Chapter 10 Exercises?

### ISSUE THREAD

**Issue by lcmpembroke** [markjprice/cs8dotnetcore3#21]
Hello Mark
I'm pleased I bought your book. Did you mean to include solutions for Chapter 10's Exercises (10.2 and 10.3) ?
Many thanks.

**Comment by markjprice** [comment]
Hi, yes, I did mean too, but life got in the way. I will provide solutions by end of November 2020. I hope you can wait till then. I will leave this issue open to remind me. p.s. I'm happy to hear you're pleased with the book.

**Comment by lcmpembroke** [comment]
Thank you Mark, that will be great.

**Comment by markjprice** [comment]
I have added solutions now. The 10.3 exercise solution not only decrypts the credit cards but also tests the salted and hashed passwords by letting you select a customer/user and attempt to "log in" as them using their password.

Remember that the password that you will need to enter to protect the file and the unprotect the file is not the passwords stored for the customers/users.
