### ISSUE TITLE
An Observation regarding using Web Services in chapter 18.

### ISSUE THREAD

**Issue by abdollahkahne** [markjprice/cs8dotnetcore3#22]
This issue is not an error and it is just an observed behavior which I decided to share it and would be greatfull for your comment.
Regrading using REST API Created in chapter 18, When I use them with HTTPS endpoints I got an error in the customers page (An error at controller's action and then page crashes regarding this error). After changing endpoint to HTTP at HTTPClient Registration at mvc project and removing HTTPS redirection at service projects this problem solved.
I am using Ubuntu and I can't use dotnet dev-certs command to register self signed certification and I trust them at browser level.
Regards

**Comment by abdollahkahne** [comment]
![Screenshot from 2020-10-27 02-20-10](https://user-images.githubusercontent.com/48277995/97236788-1ca90080-17fb-11eb-8918-cd4e3f23f131.png)
![Screenshot from 2020-10-27 02-20-31](https://user-images.githubusercontent.com/48277995/97236789-1dda2d80-17fb-11eb-8533-fd4ef44e0364.png)

**Comment by markjprice** [comment]
Hi, and thanks for your observation. 

As Scott Hanselman says, "On Linux there isn't a standard way across distros to trust the certificate, so you'll need to perform the distro specific guidance for trusting the development certificate."

https://www.hanselman.com/blog/developing-locally-with-aspnet-core-under-https-ssl-and-selfsigned-certs

Here are some articles that might help.

https://andrewlock.net/creating-and-trusting-a-self-signed-certificate-on-linux-for-use-in-kestrel-and-asp-net-core/

https://security.stackexchange.com/questions/226534/how-can-i-create-and-use-self-signed-server-certificate

I hope to have time to write an article about doing development on Linux with my book and that would include solving this issue. My instinct tells me the best solution might be using a CA like Let's Encrypt.
