### ISSUE TITLE
Chapter 2, page 58

### ISSUE THREAD

**Issue by Semro** [markjprice/cs8dotnetcore3#24]
Replace: `dotnet new console -lang "F#" -name "ExploringConsole"`
with `dotnet new console -lang "F#" --name "ExploringConsole"`
The command needs an extra dash before the `name`.

P.S. I've submitted this errata in September to Packt Customer Care, but I still don't know if it reached you.

**Comment by markjprice** [comment]
No, sadly it did not reach me, but we did spot it while creating the fifth edition so it is correct there. Luckily this was just an example of passing arguments, in fact I used to use a fictional example, not actually teaching that actual command.
