### ISSUE TITLE
Pg 113 - ME is Maine, not Maryland

### ISSUE THREAD

**Issue by will-wardlaw** [markjprice/cs8dotnetcore3#26]
A very small nitpick in a code example on Page 113.  In the switch statement there's a case that says:

```C#
    case "ME": // Maryland
```

ME is the standard abbreviation for Maine.  MD is the abbreviation for Maryland.  They're easy to confuse between starting with the same two letters and both being known for their crustacean-based seafood.

**Comment by markjprice** [comment]
Fixed in code solution and added to errata for both fourth and fifth editions.

**Comment by will-wardlaw** [comment]
Thanks, and sorry to be so nitpicky.  Great book!
