### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by zhizhang1977** [markjprice/cs8dotnetcore3#28]
Hello @markjprice .My name is zhizhang.
First thank you for your "C# 8.0 and .NET Core 3.0: Modern Cross-Platform Development, 4th Edition".
Recently, I meet a problem.In chapter 11th, use Entity Framework core to process database, I can't download the sqlite3. I input "https://www.sqlite.org/download.html" or "https://sqlite.org/download.html" or search through search engine, but I can't open the website.Please indicate me to continue.
Thank you again.

Another problem, execute "sqlite3 Northwind.db < Northwind.sql" ,vscode warn as following:
“<”运算符是为将来使用而保留的。
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : RedirectionNotSupported
Forget it, I download your db to use.

I am sorry for disturb you.Thanks.

**Comment by markjprice** [comment]
This errata might help you: https://github.com/markjprice/cs8dotnetcore3/blob/master/errata.md#page-363---creating-the-northwind-sample-database-for-sqlite
