### ISSUE TITLE
NuGet package install issues

### ISSUE THREAD

**Issue by GuildOfCalamity** [markjprice/cs8dotnetcore3#31]
PacktLibrary.dll is not available for the csproj files. There are a ton of Packt CS8 nuget packages. Which one is the core package that contains "PacktLibrary.dll"?

Trying to resolve build issues from "using Packt.Shared;" in the source classes.

**Comment by markjprice** [comment]
<PackageReference Include="packt.cs8.sharedlibrary" Version="1.0.0" />

**Comment by GuildOfCalamity** [comment]
Thanks!

I didn't realize that you need to go into the **\Chapter06\PacktLibrary** project first and build that DLL.

**Comment by GuildOfCalamity** [comment]
I had to add the DLL manually as a reference to the project to get it to work. Not sure why the NuGet manager can't install the "Packt.CS8.SharedLibrary" normally.

**Comment by markjprice** [comment]
The point of that section is not to reference the class library project. The point is to compile, package, and publish the class library to the public NuGet feed and then reference that package from the console app. If you're fixing the errors by directly referencing the class library then your bypassing the issue. Are you able to reference any other NuGet packages like Newtonsoft.Json? Can you please include your .csproj so I can see your references? It should look like this: https://github.com/markjprice/cs8dotnetcore3/blob/e1594f2caf6e952b5a72332f49a379c33012c4d2/Chapter07/AssembliesAndNamespaces/AssembliesAndNamespaces.csproj#L10

**Comment by GuildOfCalamity** [comment]
OK, I think I must've built them out of order; I was reading chapter 6 and then opened the PeopleApp project.
Thanks for you help. Great book!

**Comment by markjprice** [comment]
Ah! When you talked about "a ton of Packt CS8 nuget packages" it sounded like your were working on Chapter 7. I should always remember to request more information before jumping to conclusions. ;-)

If you download solution projects, like PeopleApp and PacktLibrary in Chapter06, then its best to always start by running "dotnet build" in the console app. That would have compiled the PacktLibrary as well as the PeopleApp and you would have avoided seeing errors for the statement: using Packt.Shared;

I will add a note to the sixth edition pointing that out. So thanks for the feedback and I hope you continue to enjoy the book.

**Comment by GuildOfCalamity** [comment]
No problem. I assumed you saw the path I included about the error "C:\me\Source Code\C# 8.0 and .Net Core 3.0\**Chapter06**"

Thanks for the "dontnet build" tip!
