### ISSUE TITLE
Downloading Northwind.sql results in an html doc

### ISSUE THREAD

**Issue by Strydir** [markjprice/cs8dotnetcore3#34]
I might be missing something.  If so, let me know and I'll delete this if needed.  (4th Ed)

Following the directions: 
"Download the script to create the Northwind database for SQLite from the following link ... sql-scripts/Northwind.sql" 
sent me down a rabbit hole as there is no "download" button.  
I ended up downloading the file from here:  ... Chapter11/WorkingWithEFCore.

As this downloads as an html file, this will result in an error when attempting to create the Northwind database, even if you've corrected the '<' error.

So Don't.  Copy the contents of the file from the original link and paste it into your own blank file and save it as something.sql

**Comment by markjprice** [comment]
This is already in the errata: https://github.com/markjprice/cs8dotnetcore3/blob/master/errata.md#page-363---creating-the-northwind-sample-database-for-sqlite
