### ISSUE TITLE
Need error info as a readme, or something.  Please support your publications.

### ISSUE THREAD

**Issue by Strydir** [markjprice/cs8dotnetcore3#35]
It's nice that you've closed the 'issues'.  Unfortunately, for people who buy your textbook, you've also removed their ability to find a solution to the errors in the 4th ed.  Now the only way for people to find a solution to the errors is to hope that they can find the solution mentioned on other sites, so you are now depending on OTHERS to support your work.
I recommend that you do a better job at supporting your own literature:  you need a readme describing the errors and what to do about them.
Disappointed.

**Comment by markjprice** [comment]
I do support my publications. All editions have an errata that is linked from the readme.md. For example, on the readme.md for the fourth edition: https://github.com/markjprice/cs8dotnetcore3
In the Important section the first link is to the errata with a list of all mistakes including the two that you highlighted. 
https://github.com/markjprice/cs8dotnetcore3#important

**Comment by Strydir** [comment]
I posted that before looking at my email and have since deleted it.  My
apologies and my thanks: that page is exactly what I was looking for!
Obviously, I had difficulty finding it but I don't really have any
suggestions on making it easier to find.  It's amazing that this resource
is available at all!
Thank you!!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by markjprice** [comment]
Thank you for replying. :) 
I will make some changes to make it easier to find the list of book corrections.
