### ISSUE TITLE
Your Book's Syntax Error in Chapter 6. 

### ISSUE THREAD

**Issue by ToruHironaka** [markjprice/cs8dotnetcore3#39]
I found your a syntax error on your book in chapter 6. See below code and my comment. I think the code in github is correct, so it is not a big deal. I just wanna report the syntax error to you. 

namespace Packt.Shared 
{ 
  public class Employee : Person 
  { 
    public string EmployeeCode { get; set; } 
    public DateTime HireDate { get; set; } 
    public void WriteToConsole()
    { 
      WriteLine(format:
        "{0} was born on {1:dd/MM/yy} and hired on {2:dd/MM/yy}",
        arg0: Name,
        arg1: DateOfBirth,
        arg2: HireDate)); <-- this should be one closed parenthese, not double. 
    }
  }
}

**Comment by markjprice** [comment]
Thanks! I have added an errata:
https://github.com/markjprice/cs8dotnetcore3/blob/master/errata.md#page-209---hiding-members
