### ISSUE TITLE
Chapter 11:  SqliteException is thrown: SQLite Error 1: 'no such table: Categories

### ISSUE THREAD

**Issue by aleksadjdj** [markjprice/cs8dotnetcore3#7]
In Chapter 11, before running project for the first time you need to set working directory. 

**To set the working directory:**
    In Solution Explorer, right click the project and then select Properties.
    Select the Debug tab in the left pane.
    Set Working directory to the project directory. 
    Navigate to Chapter11\WorkingWithEFCore folder
    Save the changes.

This should fix the problem.

**Comment by markjprice** [comment]
It sounds like you are using Visual Studio 2019. These steps are not needed if using Visual Studio Code.

**Comment by kenthub** [comment]
I'm using VS 2019. Was there an answer on how to resolve this seeing as I'm having the same issue?

**Comment by markjprice** [comment]
Yes, the original post explained how to fix the problem.

**Comment by kenthub** [comment]
Thanks, I was right-clicking on the solutions file, not the project file, to get to the properties setting. It is running now.
