### ISSUE TITLE
Chapter 08 - Page 281 - Error

### ISSUE THREAD

**Issue by Jammod** [markjprice/cs8dotnetcore3#9]
On step 3 you have the following code:

```
WriteLine("Assembly metadata:");
Assembly = Assembly.GetEntryAssembly();
WriteLine($" Full name: {assembly.FullName}");
WriteLine($" Location: {assembly.Location}");
var attributes = assembly.GetCustomAttributes();
WriteLine($" Attributes:");
foreach (Attribute a in attributes)
{
 WriteLine($" {a.GetType()}");
}
```

Line 2 shows `Assembly = Assembly.GetEntryAssembly();` but `Assembly` is a type that is being used like a variable. I believe this should be changed to `Assembly assembly = Assembly.GetEntryAssembly();`

**Comment by markjprice** [comment]
Yes, you're right. It's correct in the file in GitHub, but wrong in the printed book. I've added this to the errata.
